{% set name = "gflex" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awickert/gFlex/archive/v{{ version }}.tar.gz
  sha256: 021326e1d51dcac5dda69bde47ea8e08845cc016b37da423f3abba3cb42810ba


build:
  number: 0
  entry_points:
    - gflex = gflex:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - scipy
    - matplotlib-base

test:
  imports:
    - gflex
  commands:
    - gflex --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awickert/gFlex
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.md
  summary: One- and two-dimensional plate bending, designed for Earth's lithosphere

extra:
  recipe-maintainers:
    - rbeucher
